api_platform:
    title: Sky Base API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header

when@prod:
    api_platform:
        enable_docs: true
        enable_entrypoint: true
        enable_swagger: true
        enable_swagger_ui: true