services:
  apache:
    build:
      dockerfile: docker/Dockerfile.dev.apache
    volumes:
      - vendor:/var/www/html/vendor
      - var:/var/www/html/var
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests:cached
      - ./bin:/var/www/html/bin:cached
      - ./migrations:/var/www/html/migrations:cached
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources:cached
      - ./templates:/var/www/html/templates:cached
      - ./.env:/var/www/html/.env
      - ./.env.dev:/var/www/html/.env.dev
      - ./.env.prod:/var/www/html/.env.prod

volumes:
  vendor:
  var: