services:
  apache:
    restart: always
    build:
      context: .
    ports:
      - '8200:80'
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: skybase
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
volumes:
  mariadb:

